---
name: "tarball-generate"

on:
  release:
    types: [created]

jobs:
  tarball-generate:
    name: "tarball-generate"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
           ./
          outPath: test.tar.gz
          
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          method: md5
          output: md5.txt
          patterns: ./*.tar.gz
          
      - name: Read md5 checksum file
        id: getmd5
        run: echo "::set-output name=md5::$(cat md5.txt)"
          
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.TOKEN }}
          id: ${{ github.event.release.id }}
          body: "MD5: "
          replacebody: false
          files: "test.tar.gz"
