---
name: "tarball-generate"

on:
  release:
    types: [created]

jobs:
  tarball-generate:
    name: "tarball-generate"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
          outPath: test.tar.gz
          
      - name: Add Test Report to Release
        uses: irongut/EditRelease@v1.2.0
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         id: ${{ github.event.release.id }}
         files: "test.tar.gz"
